### ISSUE TITLE
⛵ Roadmap for version 1.2.

### ISSUE THREAD

**Issue by diamantdev** [diamantdev/BooblBot#2]
There is the roadmap for the 1.2 release:

## Main changes:
This will be part at 100% of the 1.2.
- [ ] 🚀 Rewrite the wikipedia integration: Instead of searching directly for a page, the command `/wiki` will do a reseach on wikipedia and then the user can choose the subject.
- [ ] ➕ 2 more series.
- [ ] 🚀 Modify the command `/setup` to be optional. (By default, use english as the final language and disable "share on channel".)
- [ ] ➕ New optional setting for server: `Allow NSFW Jokes` (false by default.)
- [ ] ➕ Add a new command: `/preference` and include `/setup` in it.
- [ ] ➕ New optional setting for users: `Default serie`. ("The original" by default.)

## Additionnal changes:
This can be part of the version 1.2.
- [ ] ➕ Add some credits to the footer of the translate embed. For example, if the user generate a joke, put on footer "Powered by..." with the service used for the API. For a message, put on footer "Original message from [@]".
- [ ] ➕ User can see the preference for themself and the server via the command `/preference see`.

## Some experimental ideas:
This is a bunch of ideas than I'll maybe experiment but not sure to be added to 1.2.
- [ ] 🚀 New "in progress" animation with emojis.
- [ ] ➕ New command: `/quote` who will generate quotes across some APIs.
